# Generated by Django 5.1.2 on 2024-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paybill', 'Paybill'), ('Till', 'Till (Buy Goods)'), ('Phone', 'Phone Number')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='till_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
