# Generated by Django 5.1.2 on 2024-11-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_quotation_subscription_plan_and_more'),
        ('services', '0002_rename_bandwidth_subscriptionplan_download_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='penalty_applied',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='installation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.subscriptionplan'),
        ),
    ]
