# Generated by Django 5.1.2 on 2024-11-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_invoice_created_at_remove_invoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customitem',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='customitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='installation_fee',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='products_total',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='customitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='rejected', max_length=10),
        ),
    ]
