from django.db import models
from django.core.exceptions import ValidationError
import random
import string
from services.models import SubscriptionPlan


class Customer(models.Model):
    customer_id = models.CharField(max_length=20, unique=True, blank=True, db_index=True)  # Auto-generated field
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    pppoe_username = models.CharField(max_length=50, blank=True)  # Can be autogenerated or manually adjusted
    pppoe_password = models.CharField(max_length=50, blank=True)  # Can be autogenerated or manually adjusted
    billing_address = models.TextField(blank=True, null=True)
    coordinates = models.CharField(max_length=50, blank=True, null=True, help_text="Format: 'latitude,longitude'")
    date_created = models.DateTimeField(auto_now_add=True)

    # Account fields
    account_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    credit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    outstanding_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    subscription_plan = models.ForeignKey(
        SubscriptionPlan, on_delete=models.SET_NULL, null=True, blank=True, related_name='customers'
    )

    def clean(self):
        # Validate coordinates format and ranges if provided
        if self.coordinates:
            try:
                lat_str, lon_str = self.coordinates.split(',')
                latitude = float(lat_str.strip())
                longitude = float(lon_str.strip())

                # Validate latitude and longitude ranges
                if not (-90 <= latitude <= 90):
                    raise ValidationError("Latitude must be between -90 and 90.")
                if not (-180 <= longitude <= 180):
                    raise ValidationError("Longitude must be between -180 and 180.")
            except ValueError:
                raise ValidationError("Coordinates must be in 'latitude,longitude' format.")

    def save(self, *args, **kwargs):
        # Auto-generate a unique customer_id if not provided
        if not self.customer_id:
            last_customer = Customer.objects.exclude(customer_id="").order_by('id').last()
            if last_customer and last_customer.customer_id.startswith('OPT'):
                customer_id_number = int(last_customer.customer_id[3:]) + 1
            else:
                customer_id_number = 1
            self.customer_id = 'OPT' + str(customer_id_number).zfill(6)  # e.g., OPT000001

        # Autogenerate PPPoE username if blank, or use customer_id
        if not self.pppoe_username:
            self.pppoe_username = self.customer_id

        # Autogenerate PPPoE password if blank
        if not self.pppoe_password:
            self.pppoe_password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))

        # Update credit and outstanding amounts based on account balance
        if self.account_balance >= 0:
            self.credit = self.account_balance
            self.outstanding_amount = 0
        else:
            self.credit = 0
            self.outstanding_amount = abs(self.account_balance)

        super(Customer, self).save(*args, **kwargs)

    def get_latitude(self):
        """Extract latitude from coordinates."""
        if self.coordinates:
            return float(self.coordinates.split(',')[0].strip())
        return None

    def get_longitude(self):
        """Extract longitude from coordinates."""
        if self.coordinates:
            return float(self.coordinates.split(',')[1].strip())
        return None

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
