# Generated by Django 5.1.2 on 2024-11-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_speed', models.CharField(max_length=50)),
                ('download_speed', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plan_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot')], default='pppoe', max_length=10)),
                ('duration', models.PositiveIntegerField()),
                ('time_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10)),
                ('data_cap', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
