# Generated by Django 5.1.2 on 2024-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='bandwidth',
            new_name='download_speed',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='upload_speed',
            field=models.CharField(default='5', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot')], default='pppoe', max_length=10),
        ),
    ]
