# Generated by Django 5.1.2 on 2024-10-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('address', models.TextField()),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_short_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mpesa_initiator_username', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_security_credential', models.TextField(blank=True, null=True)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_transaction_type', models.CharField(default='CustomerPayBillOnline', max_length=50)),
                ('mpesa_callback_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mpesa_confirmation_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mpesa_validation_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mpesa_timeout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mpesa_result_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mpesa_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
                ('textsms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('textsms_sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('textsms_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50)),
            ],
        ),
    ]
