# Generated by Django 5.1.2 on 2024-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
