# Generated by Django 5.1.2 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_callback_url',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_confirmation_url',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_initiator_username',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_result_url',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_security_credential',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_timeout_url',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_transaction_type',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='mpesa_validation_url',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='textsms_api_key',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='textsms_sender_id',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='textsms_url',
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='pop3_port',
            field=models.PositiveIntegerField(default=995),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='mpesa_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
