# Generated by Django 5.1.2 on 2024-11-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_organizationsettings_mpesa_callback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='customer_prefix',
            field=models.CharField(blank=True, help_text='Prefix for customer IDs', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='employee_prefix',
            field=models.CharField(blank=True, help_text='Prefix for employee IDs', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='invoice_notes',
            field=models.TextField(blank=True, help_text='Default notes to be attached to invoices', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='invoice_number_format',
            field=models.CharField(blank=True, help_text='Format for invoice numbering, e.g., INV-{number}', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, help_text='Prefix for invoice numbers', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='quote_notes',
            field=models.TextField(blank=True, help_text='Default notes to be attached to quotes', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='quote_number_format',
            field=models.CharField(blank=True, help_text='Format for quote numbering, e.g., QTE-{number}', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='quote_prefix',
            field=models.CharField(blank=True, help_text='Prefix for quote numbers', max_length=10, null=True),
        ),
    ]
