# Generated by Django 5.1.2 on 2024-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_organizationsettings_customer_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_account_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_command_id',
            field=models.CharField(choices=[('BusinessPayBill', 'BusinessPayBill'), ('BusinessBuyGoods', 'BusinessBuyGoods')], default='BusinessPayBill', max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_initiator_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_queue_timeout_url_production',
            field=models.URLField(blank=True, help_text='Production B2B timeout URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_queue_timeout_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox B2B timeout URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_receiver_party',
            field=models.CharField(blank=True, help_text='Receiver shortcode or till number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_result_url_production',
            field=models.URLField(blank=True, help_text='Production B2B result URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_result_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox B2B result URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_security_credential',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2b_short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_command_id',
            field=models.CharField(choices=[('BusinessPayment', 'BusinessPayment'), ('SalaryPayment', 'SalaryPayment'), ('PromotionPayment', 'PromotionPayment')], default='BusinessPayment', max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_initiator_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_queue_timeout_url_production',
            field=models.URLField(blank=True, help_text='Production B2C timeout URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_queue_timeout_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox B2C timeout URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_result_url_production',
            field=models.URLField(blank=True, help_text='Production B2C result URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_result_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox B2C result URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_security_credential',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_b2c_short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_confirmation_url_production',
            field=models.URLField(blank=True, help_text='Production confirmation URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_confirmation_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox confirmation URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_response_type',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_transaction_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_validation_url_production',
            field=models.URLField(blank=True, help_text='Production validation URL', null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='mpesa_validation_url_sandbox',
            field=models.URLField(blank=True, help_text='Sandbox validation URL', null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='customer_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='employee_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='imap_port',
            field=models.PositiveIntegerField(blank=True, default=993, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='invoice_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='invoice_number_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='mpesa_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', help_text='Select environment for Mpesa API', max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='pop3_port',
            field=models.PositiveIntegerField(blank=True, default=995, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='quote_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='quote_number_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='quote_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
