# Generated by Django 5.1.2 on 2024-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customer',
            name='coordinates',
            field=models.CharField(blank=True, help_text="Format: 'latitude,longitude'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
