# Generated by Django 5.1.2 on 2024-11-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_pppoe_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
