# Generated by Django 5.1.2 on 2024-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_account_balance_customer_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='last_name', max_length=255),
            preserve_default=False,
        ),
    ]
